//'ESP', 'GAL', 'CAT', 'EUS', 'POR', 'ENG', 'FRA', 'ITA', 'AST', 'DEU', 'BRA', 'VAL'
lang=[];
lang['ESP']={};
lang['GAL'] = {
"Comprobar el resultado":"Comprobar o resultado",
"CORRECTO":"Correcto",
"INCORRECTO":"Incorrecto",
"Tu respuesta":"A túa resposta",
"Abre en nueva ventana":"Abre en nova xanela",
"Escuchar":"Escoitar",
"Saber más":"Saber máis",
"Reproducir sonido":"Reproducir son",
"Panel":"Panel",
"Página":"Páxina",
"Intentos":"Intentos",
"Resultado":"Resultado",
"Descripción":"Descrición",
"Autoría":"Autoría",
"Error en el archivo de datos":"Erro no arquivo de datos",
"Error en los datos<p>Código 2</p><p style='font-size:12'>":"Erro nos datos<p>Código 2</p><p style='font-size:12'>",
"La estructura de los datos no es correcta":"A estrutura dos datos non é correcta",
"Error en los datos":"Erro nos datos",
"H":"H",
"M":"M",
"Imprimir":"Imprimir",
"Cerrar":"Pechar",
"Pausa":"Pausa",
"Parar":"Parar",
"botón para poner o quitar la pantalla completa":"botón para poñer ou quitar a pantalla completa",
"botón para mostrar el informe":"botón para amosar o informe",
"botón para avanzar página":"botón para ir á páxina seguinte",
"botón para retroceder página":"botón para ir á páxina anterior",
"botón para mostrar el menú del libro":"botón para amosar o menú do libro",
"botón para ocultar o mostrar la barra lateral":"botón para ocultar ou amosar a barra lateral",
"botón para mostrar documento de ayuda":"botón para amosar o documento de axuda",
"Imagen":"Imaxe"
};
lang['POR'] = {
"Comprobar el resultado":"Verifica o resultado",
"CORRECTO":"CORRETO",
"INCORRECTO":"INCORRETO",
"Tu respuesta":"A tua resposta",
"Abre en nueva ventana":"Abre uma nova janela",
"Escuchar":"Ouvir",
"Saber más":"Saber mais",
"Reproducir sonido":"Reproduzir som",
"Panel":"Painel",
"Página":"Página",
"Intentos":"Tentativas",
"Resultado":"Resultado",
"Descripción":"Descrição",
"Autoría":"Autoria",
"Error en el archivo de datos":"Erro no arquivo de dados",
"Error en los datos<p>Código 2</p><p style='font-size:12'>":"Erro nos dados <p> Código 2 </p> <p style = 'font-size: 12'>",
"La estructura de los datos no es correcta":"A estrutura de dados não está correta",
"Error en los datos":"Erro de dados",
"H":"H",
"M":"M",
"Imprimir":"Imprimir",
"Cerrar":"Fechar",
"Pausa":"Pausa",
"Parar":"Parar",
"botón para poner o quitar la pantalla completa":"botão para colocar ou remover a tela cheia",
"botón para mostrar el informe":"botão para mostrar o relatório",
"botón para avanzar página":"botão de avanço de página",
"botón para retroceder página":"botão voltar página",
"botón para mostrar el menú del libro":"botão para exibir o menu do livro",
"botón para ocultar o mostrar la barra lateral":"botão para ocultar ou mostrar a barra lateral",
"botón para mostrar documento de ayuda":"botão para exibir o documento de ajuda",
"Imagen":"Imagem"
};
lang['ENG'] = {
"Comprobar el resultado":"Check",
"CORRECTO":"Correct",
"INCORRECTO":"Incorrect",
"Tu respuesta":"Your answer",
"Abre en nueva ventana":"",
"Escuchar":"",
"Saber más":"",
"Reproducir sonido":"",
"Panel":"",
"Página":"",
"Intentos":"",
"Resultado":"",
"Descripción":"",
"Autoría":"",
"Error en el archivo de datos":"",
"Error en los datos<p>Código 2</p><p style='font-size:12'>":"",
"La estructura de los datos no es correcta":"",
"Error en los datos":"Error",
"Imprimir":"Print",
"Cerrar":"Close",
"Pausa":"Pause",
"Parar":"Stop"
};		